### ISSUE TITLE
Tractor Beams and Course

### ISSUE THREAD

**Issue by sinthralas** [Hatchie-Studio/lotstracker#31]
(OOC) Takeed: why is tractor not working????
(OOC) Takeed: why isn't most of this shit not working????
(OOC) Takeed: I also have 100% on eirik with all piloting that matters and I tried 29 times to COURSE for bespin and FAILED
(OOC) Takeed: IN A ROW! :D

Any known issues with using tractor beam and course? I actually watched the tractor beam fail, and Eirik has ( 100% ) on all piloting skills sans bombard ( 60% ) and carriers ( 0% ).

**Comment by michaelirick** [comment]
This was caused by integer division between the ship's tractor beam stat and the target's speed yielding 0 which was multiplied by the skill to produce 0. Fixed.
