### ISSUE TITLE
Codecrack, openhatch problem

### ISSUE THREAD

**Issue by matt1672** [Hatchie-Studio/lotstracker#40]
Not sure if this is a problem with regular ships or just the Jawa Sandcrawler on Tatooine.

I went to open it and it gave me the "Hey! That's not your ship!" message.  So I used codecrack to get the password.  Used 'open sandcrawler -password-' and still got the not your ship message.

Each time I codecrack it, I get a different password needed, and none of them work to open it.  Password on it changing constantly with not enough time to use the password to open it?

Thanks!

**Comment by matt1672** [comment]
Seems it doesn't work with other ships either.  Tried to codecrack a regular ship, got the same password each time I did it, but that password 'open ship 1220' gives me the "Hey! That's not your ship!" message. and won't let me open it like it used to.

**Comment by pqueen** [comment]
Got to type the number n open

Sent from the Yahoo Mail app. Get yours! 
 
  On Tue, Mar 6, 2018 at 2:17 PM, matt1672<notifications@github.com> wrote:   
Not sure if this is a problem with regular ships or just the Jawa Sandcrawler on Tatooine.

I went to open it and it gave me the "Hey! That's not your ship!" message. So I used codecrack to get the password. Used 'open sandcrawler ' and still got the not your ship message.

Each time I codecrack it, I get a different password needed, and none of them work to open it. Password on it changing constantly with not enough time to use the password to open it?

Thanks!

**Comment by matt1672** [comment]
I realize how it's supposed to work.  'open ship -password-'

What I'm saying is.  It's not working that way currently.

**Comment by Thanatoslots** [comment]
The sandcrawler is designed not to be cracked but it seems this issue happens with normal ships and it seems doesn't even zap a player for putting in an incorrect code.

**Comment by michaelirick** [comment]
This is fixed :)
