### ISSUE TITLE
title addition

### ISSUE THREAD

**Issue by matt1672** [Hatchie-Studio/lotstracker#41]
Could add a line to do_title to show your current title string with color codes.

Example:

'title'

Your current title is: &WBlah &Cblah blah blah&w
Change your title to what?

Thanks!

**Comment by pqueen** [comment]
I don't log in that much. But not sure by you mean to add to my title

Sent from the Yahoo Mail app. Get yours! 
 
  On Thu, Mar 8, 2018 at 9:09 AM, matt1672<notifications@github.com> wrote:   
Could add a line to do_title to show your current title string with color codes.

Example:

'title'

Your current title is: &WBlah &Cblah blah blah&w
Change your title to what?

Thanks!

**Comment by matt1672** [comment]
I'm meaning that when someone uses the title command with nothing after it.  So if they just type 'title'

It would be nice if it showed what their current character title is with color codes displayed.

**Comment by pqueen** [comment]
Are you trying to use thing that hide your name?

Sent from the Yahoo Mail app. Get yours! 
 
  On Thu, Mar 8, 2018 at 10:57 AM, matt1672<notifications@github.com> wrote:   
I'm meaning that when someone uses the title command with nothing after it. So if they just type 'title'

It would be nice if it showed what their current character title is with color codes displayed.

**Comment by pqueen** [comment]
Let me log on and I will help as best as I can

Sent from the Yahoo Mail app. Get yours! 
 
  On Thu, Mar 8, 2018 at 9:09 AM, matt1672<notifications@github.com> wrote:   
Could add a line to do_title to show your current title string with color codes.

Example:

'title'

Your current title is: &WBlah &Cblah blah blah&w
Change your title to what?

Thanks!

**Comment by matt1672** [comment]
I'm not trying to do anything with it.  I'm asking that a coder, add something to the code so that when someone types 'title' by itself that it display what your current title is, with color codes displayed.

**Comment by michaelirick** [comment]
This is a great idea. Added to the list.

**Comment by michaelirick** [comment]
This done. Enjoy.
