### ISSUE TITLE
Help File Request: Holsters

### ISSUE THREAD

**Issue by IanarT** [Hatchie-Studio/lotstracker#43]
Help Holsters/Holster/Draw.

Syntax: Holster
Syntax: Draw

A holster provides easy access and storage for two weapons. To put away your weapons, use the command holster. To take out your weapons, use the draw command.

Note: Weapons in holsters are not counted as contraband.

**Comment by pqueen** [comment]
Yes it is at first but after that it is not

Sent from the Yahoo Mail app. Get yours! 
 
  On Thu, Mar 8, 2018 at 9:33 AM, IanarT<notifications@github.com> wrote:   
Help Holsters/Holster/Draw.

Syntax: Holster
Syntax: Draw

A holster provides easy access and storage for two weapons. To put away your weapons, use the command holster. To take out your weapons, use the draw command.

Note: Weapons in holsters are not counted as contraband.

**Comment by IanarT** [comment]
I hate to say it, but no. I've tested it. Unless I've been really unlucky/stupid, holstered weapons do not count as contraband. We can leave that off the help file though if need be. No worries there.

**Comment by michaelirick** [comment]
I can confirm that holstered weapons are not treated as contraband, but they also do not count towards smuggling. Added to the list, thanks.

**Comment by Thanatoslots** [comment]
This is done.
