### ISSUE TITLE
Blimph

### ISSUE THREAD

**Issue by IanarT** [Hatchie-Studio/lotstracker#44]
@michaelirick Hi Drozel.

Blimph 3 has a coordinates of 55000 -3000 4890.

This is outside that zone you spoke of. Tried to go there and it stopped me.

EDIT: Ok, it didn't stop me:
calc blimph 55300 -3000 4890
hyp
Coordinates out of bounds!

You push forward the hyperspeed lever.
The ship lurches slightly as it makes the jump to lightspeed.
The stars become streaks of light as you enter hyperspace.

[Ship Computer] Hyperjump complete.
The ship lurches slightly as it comes out of hyperspace.
Speed: 25  Hull: 100%  Shields: 0%  Energy: 96%  
Coordinates in Blimph System system: 55300 -3000 4890

Thanks.

**Comment by IanarT** [comment]
I believe Roche is the same. -14087 -8620 83294.
I'm not sure about Kamino as I have only been once, but something is telling me that is over the 50k mark as well.

**Comment by michaelirick** [comment]
Fixed. Thanks.
