### ISSUE TITLE
Feature: doiknow

### ISSUE THREAD

**Issue by matt1672** [Hatchie-Studio/lotstracker#47]
How about a 'doiknow' command or something similiar.  Where you can say 'doiknow Stavros' and it will tell you what they've been introduced to you as, or if you haven't been introduced to you yet.

For those of us that forget what people are intro'd as and we're talking to another person.

**Comment by michaelirick** [comment]
Thanks, added to the list.

**Comment by michaelirick** [comment]
Now available in the player portal
